name: build-test

on:
  push:
    paths:
      - "node/22/bookworm-slim/Dockerfile"
      - "node/22/bookworm-slim/entrypoint.sh"
      - ".github/workflows/node-22--bookworm-slim.yml"

  pull_request:
    paths:
      - "node/22/bookworm-slim/Dockerfile"
      - "node/22/bookworm-slim/entrypoint.sh"
      - ".github/workflows/node-22--bookworm-slim.yml"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          context: .
          file: ./node/22/bookworm-slim/Dockerfile
          tags: node:22-bookworm-slim

      - name: Test for node version
        run: |
          image_node_version=$(docker run --rm node:22-bookworm-slim node --print "process.versions.node")
          echo "Expected: \"22.14.0\", Got: \"${image_node_version}\""
          [ "${image_node_version}" == "22.14.0" ]
